/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void
calculadora_1(char *host, int valor1, char op, int valor2)
{
	CLIENT *clnt;
	double *resDouble;
	int *resInt;
	bool_t esInt=FALSE;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, CALCULADORAVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	switch(op){
		case '+':{
			resDouble = suma_1(valor1, valor2, clnt);
			esInt=FALSE;
			break;
		}

		case'-':{
			resDouble = resta_1(valor1, valor2, clnt);
			esInt=FALSE;
			break;
		}

		case '/':{
			resDouble = div_1(valor1, valor2, clnt);
			esInt=FALSE;
			break;		
		}

		case '*':{
			resDouble = mult_1(valor1, valor2, clnt);
			esInt=FALSE;
			break;
		}

		case 'l':{
			resDouble = log_1(valor1, valor2, clnt);
			esInt=FALSE;
			break;
		}

		case 'p':{
			resInt = primo_1(valor1, clnt);
			esInt=TRUE;
			break;
		}

		case '%':{
			resInt = modulo_1(valor1, valor2, clnt);
			esInt=TRUE;
			break;
		}

		case '^':{
			resInt = pow_1(valor1, valor2, clnt);
			esInt=TRUE;
			break;
		}
		
		case 'v':{
			resDouble=sqrt_1(valor1, clnt);
			esInt=FALSE;
			break;
		}
	}

	
	if (resDouble == (double *) NULL && !esInt==TRUE) {
		clnt_perror (clnt, "call failed");
	}

	else 	if (resInt == (int *) NULL && esInt==FALSE) {
		clnt_perror (clnt, "call failed");
	}

	if(esInt==TRUE){
		printf("Resultado: %d\n", *resInt);
	}
	else
		printf("Resultado: %f\n", *resDouble);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	
	host = argv[1];
	int v1=atoi(argv[2]);
	int v2=atoi(argv[4]);
	calculadora_1 (host, v1, argv[3][0], v2);
exit (0);
}
