/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <time.h>

void calculadora_1(char *host, double valor1, char op, double valor2, char *comandos, matrix *m1, matrix *m2)
{
	CLIENT *clnt;
	double *res;
	int *resI;
	int esDouble = 1;
	matrix *aux;

#ifndef DEBUG
	clnt = clnt_create(host, CALCULADORA, CALCULADORAVER, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	switch (op)
	{
	case '+':
	{
		res = suma_1(valor1, valor2, clnt);

		break;
	}

	case '-':
	{
		res = resta_1(valor1, valor2, clnt);

		break;
	}

	case '/':
	{
		res = division_1(valor1, valor2, clnt);

		break;
	}

	case '*':
	{
		res = mult_1(valor1, valor2, clnt);

		break;
	}

	case 'l':
	{
		res = logaritmo_1(valor1, valor2, clnt);

		break;
	}

	case 'p':
	{
		resI = esprimo_1(valor1, clnt);
		esDouble = 0;
		break;
	}

	case '%':
	{
		resI = modulo_1(valor1, valor2, clnt);
		esDouble = 0;
		break;
	}

	case '^':
	{
		resI = potencia_1(valor1, valor2, clnt);
		esDouble = 0;
		break;
	}

	case 'v':
	{
		res = raizcuadrada_1(valor1, clnt);
		break;
	}

	case '!':
	{
		resI = factorial_1(valor1, clnt);
		esDouble=0;
		break;
	}

	case 'S':{
		printf("Entro en el cliente\n");
		aux=sumamatricial_1(*m1, *m2, clnt);

		printf("RESULTADOS:     S;LDFK;SDLFKS;DFK\n");
		for(int i=0; i<aux->fil; i++){
			for(int j=0; j<aux->col; j++)
				printf("%f ", aux->m[i][j]);

			printf("\n");
		}

		break;
	}
	}

	if (res == (double *)NULL && resI == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}

	printf("###################################\n");
	if (esDouble == 1)
		printf("Resultado: %lf\n", *res);
	else
		printf("Resultado: %d\n", *resI);

	printf("###################################\n\n");

#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[])
{
	char *host;

	if (argc < 2)
	{
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	else if (argc == 2)
	{ // Modo interactivo
#define OPCIONES 11
#define SALIDA 200
		char op[OPCIONES] = {'+', '-', '*', '/', '%', 'v', 'l', 'p', '^', '!', 'S'};
		int opcion;
		matrix m1, m2;
/*		do
		{
			do
			{
				printf("Modo interactivo. Seleccione opcion:\n");
				printf("1.- Suma\n");
				printf("2.- Resta\n");
				printf("3.- Multiplicacion\n");
				printf("4.- Division\n");
				printf("5.- Modulo\n");
				printf("6.- Raiz cuadrada\n");
				printf("7.- Logaritmo (WIP)\n");
				printf("8.- Es primo\n");
				printf("9.- Potencia\n");
				printf("10.- Factorial\n");
				printf("11.- Suma matricial\n");
				printf("12.- Multiplicacion matricial\n");
				printf("13.- Traspuesta de una matriz\n");
				printf("14.- Determinante de una matriz\n");
				printf("15.- Resolvedor de sistemas de ecuaciones\n");
				printf("%d.- Salir del programa\n", SALIDA);
				printf("Introduzca la opcion: ");
				scanf("%d", &opcion);

				if ((opcion > OPCIONES || opcion < 1) && opcion != SALIDA)
					printf("Opcion incorrecta");
			} while ((opcion > OPCIONES || opcion < 1) && opcion != SALIDA);

			// Separar los operadores unarios de los binarios
			if (opcion != SALIDA)
			{
				double valorL, valorR;

				switch (opcion)
				{
				case 1:
				case 2:
				case 3:
				case 4:
				case 5:
				case 7:
				case 9:
					printf("Primer valor: ");
					scanf("%lf", &valorL);

					printf("Segundo valor: ");
					scanf("%lf", &valorR);
					break;

				case 6:
				case 8:
				case 10:
					printf("Valor: ");
					scanf("%lf", &valorL);
					break;
				}

				calculadora_1(argv[1], valorL, op[opcion - 1], valorR, NULL, NULL, NULL);
			}
		} while (opcion != SALIDA);*/

		m1.fil=m1.col=3;
		m1.m=malloc(m1.fil*sizeof(row));

		m1.m[0]=malloc(m1.fil*m1.col*sizeof(double));

		for(int i=1; i<m1.fil; i++)
			m1.m[i]=m1.m[i-1]+m1.col;

		m2.fil=m2.col=3;
		m2.m=malloc(m2.fil*sizeof(row));

		m2.m[0]=malloc(m2.fil*m2.col*sizeof(double));

		for(int i=1; i<m2.fil; i++)
			m2.m[i]=m2.m[i-1]+m2.col;
		
		srand(time(NULL));

		for(int i=0; i<m1.fil; i++){
			for(int j=0; j<m1.col; j++){
				m1.m[i][j]=rand()%20;
				m2.m[i][j]=rand()%21;
			}
		}
				
		for(int i=0; i<m1.fil; i++){
			for(int j=0; j<m1.col; j++)
				printf("%f ", m1.m[i][j]);

			printf("\n");
		}


		printf("\n");

		for(int i=0; i<m2.fil; i++){
			for(int j=0; j<m2.col; j++)
				printf("%f ", m2.m[i][j]);

			printf("\n");
		}		

		printf("\n");

		calculadora_1(argv[1], 69, 'S', 69, NULL, &m1, &m2);


		free(m1.m[0]);
		free(m2.m[0]);
		free(m1.m);
		free(m2.m);
	}
	else
	{ // Modo con parametros
	}
	/*
		host = argv[1];
		int v1 = atof(argv[2]);
		int v2 = atof(argv[4]);
		calculadora_1(host, v1, argv[3][0], v2);
	*/
	exit(0);
}
