/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

int *
suma_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static int  result=arg1+arg2;

	return &result;
}

int *
resta_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static int  result=arg1-arg2;	

	return &result;
}

int *
mult_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static int  result=arg1*arg2;

	return &result;
}

double *
div_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static double  result=(1.0*arg1)/arg2;

	return &result;
}

int *
pow_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static int  result=1;

	for(int i=0; i<arg2; i++)
		result*=arg1;

	
	return &result;
}

int *
primo_1_svc(int arg1,  struct svc_req *rqstp)
{
	static int  result=0;

	for(int i=2; i<=arg1/2; i++)
		if(arg1%i==0)
			result=-1;

	return &result;
}

double *
sqrt_1_svc(double arg1,  struct svc_req *rqstp)
{
	static double  result=69;

	return &result;
}

double *
log_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static double  result=69;

	return &result;
}
