/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void
calculadora_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	int suma_1_arg1;
	int suma_1_arg2;
	int  *result_2;
	int resta_1_arg1;
	int resta_1_arg2;
	int  *result_3;
	int mult_1_arg1;
	int mult_1_arg2;
	double  *result_4;
	int div_1_arg1;
	int div_1_arg2;
	int  *result_5;
	int pow_1_arg1;
	int pow_1_arg2;
	int  *result_6;
	int primo_1_arg1;
	double  *result_7;
	double sqrt_1_arg1;
	double  *result_8;
	int log_1_arg1;
	int log_1_arg2;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, CALCULADORAVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = suma_1(suma_1_arg1, suma_1_arg2, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = resta_1(resta_1_arg1, resta_1_arg2, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = mult_1(mult_1_arg1, mult_1_arg2, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = div_1(div_1_arg1, div_1_arg2, clnt);
	if (result_4 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = pow_1(pow_1_arg1, pow_1_arg2, clnt);
	if (result_5 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = primo_1(primo_1_arg1, clnt);
	if (result_6 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = sqrt_1(sqrt_1_arg1, clnt);
	if (result_7 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_8 = log_1(log_1_arg1, log_1_arg2, clnt);
	if (result_8 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calculadora_1 (host);
exit (0);
}
